//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnrollmentSystem.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EnrollmentSystem.Application.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one student must be enrolled.
        /// </summary>
        public static string AtLeastOneStudentMustBeEnrolled {
            get {
                return ResourceManager.GetString("AtLeastOneStudentMustBeEnrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CourseId must be greater than zero.
        /// </summary>
        public static string CourseIdGreaterThanZero {
            get {
                return ResourceManager.GetString("CourseIdGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course with ID {0} not found.
        /// </summary>
        public static string CourseNotFound {
            get {
                return ResourceManager.GetString("CourseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student is already enrolled to this course.
        /// </summary>
        public static string EnrollmentExists {
            get {
                return ResourceManager.GetString("EnrollmentExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment not found for Student ID {0} in Course ID {1}.
        /// </summary>
        public static string EnrollmentNotFound {
            get {
                return ResourceManager.GetString("EnrollmentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade is required.
        /// </summary>
        public static string GradeRequired {
            get {
                return ResourceManager.GetString("GradeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid grade. Allowed values are A, B, C, D, F.
        /// </summary>
        public static string InvalidGrade {
            get {
                return ResourceManager.GetString("InvalidGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Student ID.
        /// </summary>
        public static string InvalidStudentID {
            get {
                return ResourceManager.GetString("InvalidStudentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No enrollments exist.
        /// </summary>
        public static string NoEnrollmentsExist {
            get {
                return ResourceManager.GetString("NoEnrollmentsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one digit.
        /// </summary>
        public static string PasswordDigit {
            get {
                return ResourceManager.GetString("PasswordDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one lowercase letter.
        /// </summary>
        public static string PasswordLowercase {
            get {
                return ResourceManager.GetString("PasswordLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters long.
        /// </summary>
        public static string PasswordMinLength {
            get {
                return ResourceManager.GetString("PasswordMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one special character.
        /// </summary>
        public static string PasswordSpecialCharacter {
            get {
                return ResourceManager.GetString("PasswordSpecialCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain at least one uppercase letter.
        /// </summary>
        public static string PasswordUppercase {
            get {
                return ResourceManager.GetString("PasswordUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed successfully.
        /// </summary>
        public static string ProcessedSuccessfully {
            get {
                return ResourceManager.GetString("ProcessedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  This field is required.
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student email is required.
        /// </summary>
        public static string StudentEmailRequired {
            get {
                return ResourceManager.GetString("StudentEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student name must not exceed 50 characters.
        /// </summary>
        public static string StudentNameMaxLength {
            get {
                return ResourceManager.GetString("StudentNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student name must be at least 3 characters long.
        /// </summary>
        public static string StudentNameMinLength {
            get {
                return ResourceManager.GetString("StudentNameMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student name cannot be empty.
        /// </summary>
        public static string StudentNameRequired {
            get {
                return ResourceManager.GetString("StudentNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Is not found.
        /// </summary>
        public static string StudentNotFound {
            get {
                return ResourceManager.GetString("StudentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
    }
}
